### ISSUE TITLE
The translated results is not showing or joining the dataset.

### ISSUE THREAD

**Issue by qifengzhou** [ChristopherLucas/translateR#12]
Hi Christopher,
I was following the manual of https://cran.r-project.org/web/packages/translateR/translateR.pdf to get translateR to work in RStudio.

I can see the dataset is printed, exactly as the original enron dataset, but no translated results shown or joined. 
plus there are no error messages. 

The code is like in the manual with the key changed to my key:
`google.dataset.out <- translate(dataset = enron,
content.field = 'email',
google.api.key = my.api.key,
source.lang = 'en',
target.lang = 'de')
print(google.dataset.out)`

Thank you for the help!
Qifeng

**Comment by vasundharaD** [comment]
Hi Qifeng

Resolved in latest code update! Will be updated on cran soon.

**Comment by qifengzhou** [comment]
Hi vasunharaD,

Thank you for the update. I tried with the new version through install_github( ). The issue remains, again I don't see the google API traffic. I talked with Lucas before, its working on his side, could be just my API problem. But its wired my API works for the other package. 
Qifeng
